# Generated by Django 5.0 on 2023-12-12 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='amodel',
            name='password',
        ),
    ]
