# Generated by Django 5.0 on 2023-12-12 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0002_remove_amodel_password'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Amodel',
            new_name='custumer',
        ),
    ]
