# Generated by Django 5.0 on 2023-12-12 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0003_rename_amodel_custumer'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='custumer',
            new_name='customer',
        ),
    ]
